config/routes.rb
Rails.application.routes.draw do
	resources :products
	resources :categories
	root to: 'home#index'

	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, autosave: true
end

app/models/product.rb
class Product < ApplicationRecord
	after_save { ProductBroadcastJob.perform_later(self) }

	belongs_to :category

	has_attached_file :photo, styles: { medium: "300x300>", thumb: "200x200>" }

	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]

	def label
		if quantity <= 3
			I18n.t(:label_danger)
		elsif quantity <= 7
			I18n.t(:label_warning)
		else
			I18n.t(:label_success)
		end
	end

	def status_label
		active? ? I18n.t(:in_stock) : (:out_of_stock)
	end
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy]

	# GET /categories
	# GET /categories.json
	def index
		@categories = Category.all
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
	end

	# GET /categories/new
	def new
		@category = Category.new
	end

	# GET /categories/1/edit
	def edit
	end

	# POST /categories
	# POST /categories.json
	def create
		@category = Category.new(category_params)

		respond_to do |format|
			if @category.save
				format.html { redirect_to @category, notice: 'Category was successfully created.' }
				format.json { render :show, status: :created, location: @category }
			else
				format.html { render :new }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /categories/1
	# PATCH/PUT /categories/1.json
	def update
		respond_to do |format|
			if @category.update(category_params)
				format.html { redirect_to @category, notice: 'Category was successfully updated.' }
				format.json { render :show, status: :ok, location: @category }
			else
				format.html { render :edit }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /categories/1
	# DELETE /categories/1.json
	def destroy
		@category.destroy
		respond_to do |format|
			format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def category_params
			params.require(:category).permit(:name)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :name, :quantity, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def company_url_address
		"http://www.agence.com.br"
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= t('layout.categories') %>: <%= @category.name %></h1>

<hr>

<div class="row">
	<div class="col-sm-12">
		<div class="row">
			<% @category.products.in_groups_of(4, false) do |products| %>
			<div class="col-sm-12">
				<div class="row">
					<%= render products, partial: "products/product" %>
				</div><!--/row-->
			</div><!--/col-12-->
			<% end %>
		</div><!--/row-->
		<p>
			<div class="btn-group">
				<% if current_user && current_user.admin? %>
					<%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-sm btn-default' %>
				<% end -%>
				<%= link_to 'Back to Home', root_path, class: 'btn btn-xs btn-default' %>
			</div>
		</p>
	</div>
</div>

app/views/home/index.html.erb
<h1><%= t('layout.home') %></h1>

<hr>

<div class="row">
	<% @products.in_groups_of(4, false) do |products| %>
	<div class="col-sm-12">
		<div class="row products">
			<%= render products, partial: "products/product" %>
		</div><!--/row-->
	</div><!--/col-12-->
	<% end %>
</div><!--/row-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= t(:application_name) %></title>
		<%= csrf_meta_tags %>

		<%= stylesheet_link_tag "application", :media => "all" %>

		<%= javascript_include_tag "application" %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
		<![endif]-->
	</head>
	<body>

		<%= nav_bar fixed: :top, brand: t(:application_name), responsive: true do %>
			<%= menu_group do %>
				<%= menu_item t('menu.home'), root_path %>
				<%= menu_divider %>
				<%= drop_down t('menu.products') do %>
					<% Category.all.each do |category| %>
						<%= menu_item category.name, category_path(category) %>
					<% end -%>
				<% end %>
				<% if current_user %>
					<%= menu_item t('devise.edit_registration'), edit_user_registration_path %>
					<%= menu_item t('devise.log_out'), destroy_user_session_path, method: :delete %>
				<% else %>
					<%= menu_item t('devise.sign_in'), new_user_session_path %>
					<%= menu_item t('devise.register'), new_user_registration_path %>
				<% end %>
			<% end %>
		<% end %>

		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<%= bootstrap_flash %>
					<%= yield %>
				</div>

		</div> <!-- /container -->
		<footer>
			<p>&copy; <%= link_to t(:company_name), company_url_address, target: "_blank" %> <%= Date.today.year %></p>
		</footer>

	</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :product_category_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :product_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<span id="product_box_<%=product.id%>">
	<div class="col-md-3">
		<div class="well">
			<div class="text-center">
				<%= image_tag product.photo.url(:thumb), class: "well_product_photo" %>
			</div>
			<h4><span class="label <%= product.label %> pull-right" id="product_status_<%=product.id%>"><%= product.status_label %></span> <%= link_to product.name, product %></h4>
			Quantity: <strong><span id="product_quantity_<%=product.id%>"><%= product.quantity %></span></strong><br />
			Category: <strong><%= product.category.name %></strong><hr />
			<%= link_to t('more_details'), product, class: "btn btn-xs btn-default" %>
		</div>
	</div>
</span>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.category %></td>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.active %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= t('layout.products') %>: <%= @product.name %></h1>
<hr />
<div class="row">
	<div class="col-sm-4">
		<%= image_tag @product.photo.url(:medium), class: "well_product_photo" %>
	</div>
	<div class="col-sm-8">
		<p>
			<strong>Category:</strong>
			<%= link_to @product.category.name, @product.category %>
		</p>

		<p>
			<strong>Quantity:</strong>
			<span id="product_quantity_<%=@product.quantity%>"><%= @product.quantity %></span>
		</p>

		<p>
			<span class="label <%= @product.label %>" id="product_status_<%=@product.id%>"><%= @product.status_label %></span>
		</p>
		<p>
			<div class="btn-group">
				<% if current_user && current_user.admin? %>
					<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-xs btn-default' %>
					<a href="javascript:;" class="btn btn-xs btn-default" id="reload_product" data-product-id="<%=@product.id%>">Update in Front</a>
				<% end -%>
				<%= link_to 'Back to Home', root_path, class: 'btn btn-xs btn-default' %>
			</div>
		</p>
	</div>
</div>
<br />